Result of overhaul by Barry Gallagher. Major rewrite. Addition of test suite.
Good day gentlemen,

Feel free to ask questions and make more suggestions about the long email below and codes attached....

Based on your emails, I added a conversion attribute which is sufficient for many of the classes.  I also wrote a unittest suite -- in which you will have to modify the imports and datapath based on where you have it located (mine works in the Pydro Trunk with the Demonstrator App).  Glen, as an aside - I used the demo-app to debug the code combined with Eclipse which worked very nicely.

I do not have knowledge (as I haven't read the .all specs) of what the recalculated checksum is but I bet it'd be easy to add to the "get_datablock" function.  I assume it's the last byte of the message that is simply skipped over in your current codes.

The unittest has two test functions for each packet type.  One for reading which compares to Glen's original implementation and one for writing/editing.  The writing/editing function takes the read data and modifies the data by adding a 1 to the numeric fields writes/reads it back then subtracts a 1 (so in theory the data is unchanged) and writes/reads that then compares to the original data.  The way it is set up you could remove the need for the original par.py and store the data as embedded strings (rather than input file) and numpy arrays (rather than using the original par.py code like I did).

The unittest shows an issue with how the data is held though.  For anything that is stored in the file as an integer but is converted to float with a scalar multiplier there is the potential for roundoff errors in the int to float back to int conversions.  I had to add a tolerance value to get the tests to pass to account for this.  My main goal was to look for major problems of the data being written with the wrong size etc.

The .all files that I have for testing do not have all the packet types -- so I need you guys to either supply some data with the packets I haven't tried or test/fix them yourselves.  Below is the unittest output which shows which datagrams I have not seen.  Also there are some sub-types like GGA for Data80 and I only had 'GRP' types for Data110.

I have spent way too much time messing around with this so am cutting off my work for now.  I've attached my revised source for your review to this point.  As you will see in the unittests, I have not finished a writer for some of the datatypes that require more customized output (Data110, Data73, Data79, Data80).  They are either binary where the data is broken up and needed special processing to read it (an the equivalent inverse to write) or ascii (like GGA) which also would take a bit more thought.

And finally, when I look at the code now -- I wonder if I obfuscated it too much, so feel free to throw it away.  I would expect to take this class structure to the reson reader in the future though since I think the interactive prompt usage will be easier and the auto-prints are helpful.

test_102_read (__main__.TestPAR) ... skipped 'Did not find data for pkt 102'
test_102_write (__main__.TestPAR) ... skipped 'Did not find data for pkt 102'
test_104_read (__main__.TestPAR) ... ok
test_104_write (__main__.TestPAR) ... ok
test_107_read (__main__.TestPAR) ... skipped 'Did not find data for pkt 107'
test_107_write (__main__.TestPAR) ... skipped 'Did not find data for pkt 107'
test_109_read (__main__.TestPAR) ... skipped 'Did not find data for pkt 109'
test_109_write (__main__.TestPAR) ... skipped 'Did not find data for pkt 109'
test_110_read (__main__.TestPAR) ... ok
test_110_write (__main__.TestPAR) ... ERROR
test_48_read (__main__.TestPAR) ... ok
test_48_write (__main__.TestPAR) ... ok
test_49_read (__main__.TestPAR) ... ok
test_49_write (__main__.TestPAR) ... ok
test_51_read (__main__.TestPAR) ... ok
test_51_write (__main__.TestPAR) ... ok
test_65_read (__main__.TestPAR) ... ok
test_65_write (__main__.TestPAR) ... ok
test_66_read (__main__.TestPAR) ... skipped 'Did not find data for pkt 66'
test_66_write (__main__.TestPAR) ... skipped 'Did not find data for pkt 66'
test_67_read (__main__.TestPAR) ... ok
test_67_write (__main__.TestPAR) ... ok
test_68_read (__main__.TestPAR) ... skipped 'Did not find data for pkt 68'
test_68_write (__main__.TestPAR) ... skipped 'Did not find data for pkt 68'
test_71_read (__main__.TestPAR) ... ok
test_71_write (__main__.TestPAR) ... ok
test_73_read (__main__.TestPAR) ... ok
test_73_write (__main__.TestPAR) ... ERROR
test_78_read (__main__.TestPAR) ... ok
test_78_write (__main__.TestPAR) ... ok
test_79_read (__main__.TestPAR) ... ok
test_79_write (__main__.TestPAR) ... ERROR
test_80_read (__main__.TestPAR) ... ok
test_80_write (__main__.TestPAR) ... ERROR
test_82_read (__main__.TestPAR) ... ok
test_82_write (__main__.TestPAR) ... ok
test_83_read (__main__.TestPAR) ... skipped 'Did not find data for pkt 83'
test_83_write (__main__.TestPAR) ... skipped 'Did not find data for pkt 83'
test_85_read (__main__.TestPAR) ... ok
test_85_write (__main__.TestPAR) ... ok
test_88_read (__main__.TestPAR) ... ok
test_88_write (__main__.TestPAR) ... ok
test_89_read (__main__.TestPAR) ... ok
test_89_write (__main__.TestPAR) ... ok

======================================================================
ERROR: test_110_write (__main__.TestPAR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\PydroTrunk\Python27_x64\lib\site-packages\HSTB\demos\Hydrographic_Python\Bathymetry\Kongsberg\test_par.py", line 323, in test_110_write
    data_back_to_original = self.writable_test(data, args=[data.time])
  File "C:\PydroTrunk\Python27_x64\lib\site-packages\HSTB\demos\Hydrographic_Python\Bathymetry\Kongsberg\test_par.py", line 97, in writable_test
    datablock = data.get_datablock()  # get a buffer string that could be written back to a file
  File "C:\PydroTrunk\Python27_x64\lib\site-packages\HSTB\drivers\par.py", line 3025, in get_datablock
    part2 = self.att_data.get_datablock()
  File "C:\PydroTrunk\Python27_x64\lib\site-packages\HSTB\drivers\par.py", line 2989, in get_datablock
    raise Exception("Need to put the Proc and Raw packets back together properly.")
Exception: Need to put the Proc and Raw packets back together properly.

======================================================================
ERROR: test_73_write (__main__.TestPAR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\PydroTrunk\Python27_x64\lib\site-packages\HSTB\demos\Hydrographic_Python\Bathymetry\Kongsberg\test_par.py", line 196, in test_73_write
    data_back_to_original = self.writable_test(data)
  File "C:\PydroTrunk\Python27_x64\lib\site-packages\HSTB\demos\Hydrographic_Python\Bathymetry\Kongsberg\test_par.py", line 97, in writable_test
    datablock = data.get_datablock()  # get a buffer string that could be written back to a file
  File "C:\PydroTrunk\Python27_x64\lib\site-packages\HSTB\drivers\par.py", line 1886, in get_datablock
    raise Exception("This data type is not exportable yet.  Need to confirm the format of the ascii data")
Exception: This data type is not exportable yet.  Need to confirm the format of the ascii data

======================================================================
ERROR: test_79_write (__main__.TestPAR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\PydroTrunk\Python27_x64\lib\site-packages\HSTB\demos\Hydrographic_Python\Bathymetry\Kongsberg\test_par.py", line 214, in test_79_write
    data_back_to_original = self.writable_test(data)
  File "C:\PydroTrunk\Python27_x64\lib\site-packages\HSTB\demos\Hydrographic_Python\Bathymetry\Kongsberg\test_par.py", line 97, in writable_test
    datablock = data.get_datablock()  # get a buffer string that could be written back to a file
  File "C:\PydroTrunk\Python27_x64\lib\site-packages\HSTB\drivers\par.py", line 2008, in get_datablock
    raise Exception("Not Implemented")
Exception: Not Implemented

======================================================================
ERROR: test_80_write (__main__.TestPAR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\PydroTrunk\Python27_x64\lib\site-packages\HSTB\demos\Hydrographic_Python\Bathymetry\Kongsberg\test_par.py", line 225, in test_80_write
    data_back_to_original = self.writable_test(data)
  File "C:\PydroTrunk\Python27_x64\lib\site-packages\HSTB\demos\Hydrographic_Python\Bathymetry\Kongsberg\test_par.py", line 97, in writable_test
    datablock = data.get_datablock()  # get a buffer string that could be written back to a file
  File "C:\PydroTrunk\Python27_x64\lib\site-packages\HSTB\drivers\par.py", line 2144, in get_datablock
    raise Exception("Not Implemented")
Exception: Not Implemented

----------------------------------------------------------------------
Ran 44 tests in 0.589s

FAILED (errors=4, skipped=12)